name: Go
on: [push]
jobs:

  spectralops:
    name: Spectral
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install
        env:
          SPECTRAL_DSN: ${{ secrets.SPECTRAL_DSN }}
        run: curl -L https://get.spectralops.io/latest/sh | sudo sh
      - name: Scan
        run: spectral run
